expense-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>Base object for the Expense Tracker 2GP app</description>
    <label>Expense</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

expense-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount incurred for the expense</description>
    <inlineHelpText>Please enter the amount of expense</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

expense-app/main/default/objects/Expense__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The country to track the expenses for. By default this should be Australia</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
                <default>true</default>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

expense-app/main/default/objects/Expense__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date of the expense</description>
    <inlineHelpText>Please select the date the expense was incurred</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

expense-app/main/default/objects/Expense__c/fields/Ledger__c.field-meta.xml
<CustomField>
    <fullName>Ledger__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ledger</label>
    <referenceTo>Ledger__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

expense-app/main/default/objects/Ledger__c/Ledger__c.object-meta.xml
<CustomObject>
    <label>Ledger</label>
    <nameField>
        <label>Ledger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

expense-app/main/default/objects/Ledger__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

expense-app/main/default/objects/Ledger__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The Date of the Ledger. The important info here is the Month and the Year as this is a Monthly Ledger</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

expense-app/main/default/objects/Re_fuel_Entry__c/Re_fuel_Entry__c.object-meta.xml
<CustomObject>
    <label>Re-fuel Entry</label>
    <nameField>
        <displayFormat>RF-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Re-fuel Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

expense-app/main/default/objects/Re_fuel_Entry__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Auto-calculated price based on price per litre and how many litres filled</description>
    <formula>Litres__c *  Price_per_litre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

expense-app/main/default/objects/Re_fuel_Entry__c/fields/Litres__c.field-meta.xml
<CustomField>
    <fullName>Litres__c</fullName>
    <label>Litres</label>
    <precision>18</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

expense-app/main/default/objects/Re_fuel_Entry__c/fields/Odometer__c.field-meta.xml
<CustomField>
    <fullName>Odometer__c</fullName>
    <label>Odometer</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

expense-app/main/default/objects/Re_fuel_Entry__c/fields/Price_per_litre__c.field-meta.xml
<CustomField>
    <fullName>Price_per_litre__c</fullName>
    <label>Price per litre</label>
    <precision>18</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

expense-app/main/default/objects/Re_fuel_Entry__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Re-fuel Entries</relationshipLabel>
    <relationshipName>Re_fuel_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

expense-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Used to track the vehicle</description>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Plate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

expense-app/main/default/objects/Vehicle__c/fields/Purchased_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchased_Date__c</fullName>
    <label>Purchased Date</label>
    <type>Date</type>
</CustomField>

expense-app/main/default/classes/TestCreateExpenseOnRefuel.cls
@isTest
private class TestCreateExpenseOnRefuel {
    @isTest
    static void testCreateExpenseOnRefuel() {
        // Set up test data
        // This is a test Refuel_Entry__c record
        
        Date dtToday = Date.today();
        String ledgerName = ExpenseTrackerTools.getLedgerName(dtToday.Year(), 
                                                              dtToday.Month(),
                                                              'Australia');

        Ledger__c testLedger = new Ledger__c(Name=ledgerName,Date__c=dtToday,Country__c='Australia'); 
        Vehicle__c testVehicle = new Vehicle__c(Name = 'DUMMYCAR',Purchased_Date__c=Date.Today());
        
		insert testLedger;
        insert testVehicle;
        // Insert the test Refuel_Entry__c record
        Re_fuel_Entry__c testRefuelEntry = new Re_fuel_Entry__c(
            Odometer__c = 900,
            Litres__c = 60.00,
            Price_per_litre__c = 2.0,
            Vehicle__c = testVehicle.Id, 
            Date__c = Date.today()
        );

        // Start the test context
        Test.startTest();
        
        insert testRefuelEntry;
        
        // Stop the test context
        Test.stopTest();

        // Query for the created Expense__c record
        List<Expense__c> expenses = [SELECT Name, Amount__c, Date__c FROM Expense__c WHERE Name = 'Costco'];
        List<Re_Fuel_Entry__c> refuelEntries = [SELECT Name, Amount__c, Date__c FROM Re_Fuel_Entry__c WHERE Vehicle__c = :testVehicle.Id];

        // Assert that one Expense__c record was created
        System.assertEquals(1, expenses.size(), 'One Expense record should be created');
        System.assertEquals(1, refuelEntries.size(), 'One Test Refuel Entry should be created');

        // Assert that the fields on the Expense__c record have the correct values
        Expense__c createdExpense = expenses[0];
        Re_Fuel_Entry__c refuelEntry = refuelEntries[0];
        System.assertEquals('Costco', createdExpense.Name, 'The Expense Name should be Costco');
        System.assertEquals(refuelEntry.Amount__c, createdExpense.Amount__c, 'The Expense Amount should match the Refuel Entry Amount');
        System.assertEquals(refuelEntry.Date__c, createdExpense.Date__c, 'The Expense Date should match the Refuel Entry Date');
    }
}