expense-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>Base object for the Expense Tracker 2GP app</description>
    <label>Expense</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

expense-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount incurred for the expense</description>
    <inlineHelpText>Please enter the amount of expense</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

expense-app/main/default/objects/Expense__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <description>Sub type of the expense</description>
    <label>Sub-Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Devices</fullName>
            </value>
            <value>
                <fullName>Donations</fullName>
            </value>
            <value>
                <fullName>Eating Out</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>Gifts</fullName>
            </value>
            <value>
                <fullName>Groceries</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>Subscriptions</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
            <value>
                <fullName>Fees</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

expense-app/main/default/objects/Expense__c/fields/Tracking_Account__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tracking Account</label>
    <referenceTo>Tracking_Account__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

expense-app/main/default/objects/Expense__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The high level expense types. Sub-types provide greater detail.</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Household</fullName>
                <default>true</default>
                <label>Household</label>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Leisure</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

expense-app/main/default/objects/Tracking_Account__c/Tracking_Account__c.object-meta.xml
<CustomObject>
    <description>Expenses and Income must be tied to a Tracking Account. 
This is used for example, to track expenses and income for Australia separate from those in Malaysia.</description>
    <label>Tracking Account</label>
    <nameField>
        <label>Tracking Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracking Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

expense-app/main/default/classes/ExpenseTrackerPostInstallUtilTest.cls
@isTest
public class ExpenseTrackerPostInstallUtilTest {
    @isTest
    static public void testOnInstall() {
        AggregateResult[] arList = [SELECT COUNT(ID) from Tracking_Account__c];
        Integer count = arList.size();
        Integer expectedResult = count;
        ExpenseTrackerPostInstallUtil obj = new ExpenseTrackerPostInstallUtil();
        obj.onInstall(null);
        arList = [SELECT COUNT(ID) from Tracking_Account__c];
        Integer actualCount = arList.size();
        System.assertEquals(expectedResult, actualCount, 'Test passed');
    }
    
    @isTest
    static public void testSetTrackingAccount() {
        ExpenseTrackerPostInstallUtil obj = new ExpenseTrackerPostInstallUtil();
        Expense__c testExpense = new Expense__c(Name='Test', 
                                                Amount__c=99, 
                                                Type__c='Household', 
                                                Sub_Type__c='Groceries'
                                                );
  
        Tracking_Account__c ta = new Tracking_Account__c(Name='Australia');
        insert ta;
        testExpense.Tracking_Account__c = ta.Id;
        insert testExpense;
        
        Tracking_Account__c tb = new Tracking_Account__c(Name='Malaysia');
		insert tb;
        
		obj.setAllTxnToTrackingAccount('Malaysia');        
        List<Expense__c> expenses = [SELECT Tracking_Account__c from Expense__c];        
        BOOLEAN pass = true;
        for (Expense__c e: expenses) {
            if (e.Tracking_Account__c != tb.Id) {
                pass = false;
            }
        }
        System.assertEquals(pass,true,'Not all records were updated');
    }
}